import requests
from bs4 import BeautifulSoup

# URL of the webpage to download
url = "http://devernay.free.fr/cours/opengl/materials.html"

# Send a GET request to the URL
response = requests.get(url)
response.raise_for_status()

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(response.content, "html.parser")
# Find the first <table> element
table = soup.find("table")
if not table:
    raise ValueError("could not find table")

print(
    f"""
// generated by gen_materials.py
// based on {url}
#include <glm/glm.hpp>

struct Material {{
  glm::vec3 ambient;
  glm::vec3 diffuse;
  glm::vec3 specular;
  float     shininess;
}};
      
Material materials[] = {{"""
)

# Loop through each <tr> row in the table
for row in table.find_all("tr")[1:]:  # skip header
    # Loop through each <td> cell in the row
    cells = row.find_all(["td", "th"])
    ents = [cell.get_text(strip=True) for cell in cells]
    material_initializer = (
        f"  {{"
        f".ambient = glm::vec3({ents[1]}, {ents[2]}, {ents[3]}), "
        f".diffuse = glm::vec3({ents[4]}, {ents[5]}, {ents[6]}), "
        f".specular = glm::vec3({ents[7]}, {ents[8]}, {ents[9]}), "
        f".shininess = {float(ents[10]) * 128} "
        f"}}, // {ents[0]}"
    )
    print(material_initializer)

print("};")
